language: python
python: 
  - "3.4"
install:
  - pip install -r requirements.txt
  - pip install flake8
  - pip install coveralls
  - pip install tensorflow
  - pip install -U git+https://github.com/conan7882/DeepVision-tensorflow.git
script:
  - flake8 . --ignore=F405,F403
  - python nerual_style/main.py --style test_data/vangogh.jpg --content test_data/cat.png --maxiter 1 --cscale 100 --rescale
  # - coverage run --source=. test.py
  # - python generate.py cv.yaml --markdown
  # - coverage run --source=. generate.py cv.yaml --markdown
# after_success:
#   - coveralls
# group:
#   - stable
# dist: 
#   - trusty
# os: 
#   - linux